openapi: 3.1.0
info:
  title: Symbiotica Notion Bridge
  version: '1.0.0'
servers:
  - url: https://4714-2605-59c0-208c-1914-fd68-befe-e50d-dfaf.ngrok-free.app
paths:
  /get-page:
    post:
      operationId: get_notion_page_by_title
      summary: Retrieve a Notion page and its content by title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the Notion page to retrieve
              required:
                - title
      responses:
        '200':
          description: Page data with content
          content:
            application/json:
              schema:
                type: object
                properties:
                  page_id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                    description: The text content of the page